from PyQt5 import *


class Ui_DialogOpen(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(813, 546)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(450, 450, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 130, 230, 240))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayoutCharacteristics = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayoutCharacteristics.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayoutCharacteristics.setContentsMargins(0, 0, 0, 0)
        self.formLayoutCharacteristics.setObjectName("formLayoutCharacteristics")
        self.strength = QtWidgets.QLabel(self.layoutWidget)
        self.strength.setObjectName("strength")
        self.formLayoutCharacteristics.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.strength)
        self.agility = QtWidgets.QLabel(self.layoutWidget)
        self.agility.setObjectName("agility")
        self.formLayoutCharacteristics.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.agility)
        self.constitution = QtWidgets.QLabel(self.layoutWidget)
        self.constitution.setObjectName("constitution")
        self.formLayoutCharacteristics.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.constitution)
        self.intelligence = QtWidgets.QLabel(self.layoutWidget)
        self.intelligence.setObjectName("intelligence")
        self.formLayoutCharacteristics.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.intelligence)
        self.wisdom = QtWidgets.QLabel(self.layoutWidget)
        self.wisdom.setObjectName("wisdom")
        self.formLayoutCharacteristics.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.wisdom)
        self.charisma = QtWidgets.QLabel(self.layoutWidget)
        self.charisma.setObjectName("charisma")
        self.formLayoutCharacteristics.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.charisma)
        self.characteristics = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.characteristics.setFont(font)
        self.characteristics.setObjectName("characteristics")
        self.formLayoutCharacteristics.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.characteristics)
        self.lcdCharisma = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdCharisma.setObjectName("lcdCharisma")
        self.formLayoutCharacteristics.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lcdCharisma)
        self.lcdWisdom = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdWisdom.setObjectName("lcdWisdom")
        self.formLayoutCharacteristics.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lcdWisdom)
        self.lcdIntelligence = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdIntelligence.setObjectName("lcdIntelligence")
        self.formLayoutCharacteristics.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lcdIntelligence)
        self.lcdConstitution = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdConstitution.setObjectName("lcdConstitution")
        self.formLayoutCharacteristics.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lcdConstitution)
        self.lcdAgility = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdAgility.setObjectName("lcdAgility")
        self.formLayoutCharacteristics.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lcdAgility)
        self.lcdStrength = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdStrength.setObjectName("lcdStrength")
        self.formLayoutCharacteristics.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lcdStrength)
        self.pointsOfCharacteristics = QtWidgets.QLabel(self.layoutWidget)
        self.pointsOfCharacteristics.setObjectName("pointsOfCharacteristics")
        self.formLayoutCharacteristics.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pointsOfCharacteristics)
        self.lcdPointOfCharacteristics = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdPointOfCharacteristics.setObjectName("lcdPointOfCharacteristics")
        self.formLayoutCharacteristics.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lcdPointOfCharacteristics)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 20, 751, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelName = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.labelName.setFont(font)
        self.labelName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelName.setObjectName("labelName")
        self.horizontalLayout_2.addWidget(self.labelName)
        self.nameOfCharacter = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.nameOfCharacter.setObjectName("nameOfCharacter")
        self.horizontalLayout_2.addWidget(self.nameOfCharacter)
        self.labelClass = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.labelClass.setFont(font)
        self.labelClass.setAlignment(QtCore.Qt.AlignCenter)
        self.labelClass.setObjectName("labelClass")
        self.horizontalLayout_2.addWidget(self.labelClass)
        self.classOfCharacter = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.classOfCharacter.setObjectName("classOfCharacter")
        self.horizontalLayout_2.addWidget(self.classOfCharacter)
        self.labelRace = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.labelRace.setFont(font)
        self.labelRace.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRace.setObjectName("labelRace")
        self.horizontalLayout_2.addWidget(self.labelRace)
        self.raceOfCharacter = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.raceOfCharacter.setObjectName("raceOfCharacter")
        self.horizontalLayout_2.addWidget(self.raceOfCharacter)
        self.labelLevel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.labelLevel.setFont(font)
        self.labelLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLevel.setObjectName("labelLevel")
        self.horizontalLayout_2.addWidget(self.labelLevel)
        self.lcdLevel = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_2)
        self.lcdLevel.setObjectName("lcdLevel")
        self.horizontalLayout_2.addWidget(self.lcdLevel)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(540, 110, 251, 321))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 20, 207, 257))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayoutForces = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayoutForces.setContentsMargins(0, 0, 0, 0)
        self.formLayoutForces.setObjectName("formLayoutForces")
        self.labelForces = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.labelForces.setFont(font)
        self.labelForces.setObjectName("labelForces")
        self.formLayoutForces.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelForces)
        self.labelBarrierOfForce = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelBarrierOfForce.setEnabled(True)
        self.labelBarrierOfForce.setObjectName("labelBarrierOfForce")
        self.formLayoutForces.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelBarrierOfForce)
        self.labelThrowOfSword = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelThrowOfSword.setObjectName("labelThrowOfSword")
        self.formLayoutForces.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelThrowOfSword)
        self.labelLightning = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelLightning.setObjectName("labelLightning")
        self.formLayoutForces.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelLightning)
        self.labelStun = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelStun.setObjectName("labelStun")
        self.formLayoutForces.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelStun)
        self.labelTelekinesis = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelTelekinesis.setObjectName("labelTelekinesis")
        self.formLayoutForces.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelTelekinesis)
        self.labelPush = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelPush.setObjectName("labelPush")
        self.formLayoutForces.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.labelPush)
        self.labelAcceleration = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelAcceleration.setObjectName("labelAcceleration")
        self.formLayoutForces.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.labelAcceleration)
        self.lcdBarrierOfForce = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.lcdBarrierOfForce.setObjectName("lcdBarrierOfForce")
        self.formLayoutForces.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lcdBarrierOfForce)
        self.lcdThrowOfSword = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.lcdThrowOfSword.setObjectName("lcdThrowOfSword")
        self.formLayoutForces.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lcdThrowOfSword)
        self.lcdLightning = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.lcdLightning.setObjectName("lcdLightning")
        self.formLayoutForces.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lcdLightning)
        self.lcdStun = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.lcdStun.setObjectName("lcdStun")
        self.formLayoutForces.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lcdStun)
        self.lcdTelekinesis = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.lcdTelekinesis.setObjectName("lcdTelekinesis")
        self.formLayoutForces.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lcdTelekinesis)
        self.lcdPush = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.lcdPush.setObjectName("lcdPush")
        self.formLayoutForces.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lcdPush)
        self.lcdAcceleration = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.lcdAcceleration.setObjectName("lcdAcceleration")
        self.formLayoutForces.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lcdAcceleration)
        self.pointOfForces = QtWidgets.QLabel(self.formLayoutWidget)
        self.pointOfForces.setObjectName("pointOfForces")
        self.formLayoutForces.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pointOfForces)
        self.lcdPointOfForces = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.lcdPointOfForces.setObjectName("lcdPointOfForces")
        self.formLayoutForces.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lcdPointOfForces)
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(270, 130, 252, 292))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.formLayoutSkills = QtWidgets.QFormLayout(self.layoutWidget_2)
        self.formLayoutSkills.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayoutSkills.setContentsMargins(0, 0, 0, 0)
        self.formLayoutSkills.setObjectName("formLayoutSkills")
        self.labelSkills = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.labelSkills.setFont(font)
        self.labelSkills.setObjectName("labelSkills")
        self.formLayoutSkills.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelSkills)
        self.lebelComputers = QtWidgets.QLabel(self.layoutWidget_2)
        self.lebelComputers.setObjectName("lebelComputers")
        self.formLayoutSkills.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lebelComputers)
        self.explosive = QtWidgets.QLabel(self.layoutWidget_2)
        self.explosive.setObjectName("explosive")
        self.formLayoutSkills.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.explosive)
        self.secrecy = QtWidgets.QLabel(self.layoutWidget_2)
        self.secrecy.setObjectName("secrecy")
        self.formLayoutSkills.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.secrecy)
        self.observation = QtWidgets.QLabel(self.layoutWidget_2)
        self.observation.setObjectName("observation")
        self.formLayoutSkills.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.observation)
        self.belief = QtWidgets.QLabel(self.layoutWidget_2)
        self.belief.setObjectName("belief")
        self.formLayoutSkills.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.belief)
        self.repair = QtWidgets.QLabel(self.layoutWidget_2)
        self.repair.setObjectName("repair")
        self.formLayoutSkills.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.repair)
        self.sistemOfSecurity = QtWidgets.QLabel(self.layoutWidget_2)
        self.sistemOfSecurity.setObjectName("sistemOfSecurity")
        self.formLayoutSkills.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.sistemOfSecurity)
        self.healing = QtWidgets.QLabel(self.layoutWidget_2)
        self.healing.setObjectName("healing")
        self.formLayoutSkills.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.healing)
        self.lcdComputers = QtWidgets.QLCDNumber(self.layoutWidget_2)
        self.lcdComputers.setObjectName("lcdComputers")
        self.formLayoutSkills.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lcdComputers)
        self.lcdExplosive = QtWidgets.QLCDNumber(self.layoutWidget_2)
        self.lcdExplosive.setObjectName("lcdExplosive")
        self.formLayoutSkills.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lcdExplosive)
        self.lcdSecrecy = QtWidgets.QLCDNumber(self.layoutWidget_2)
        self.lcdSecrecy.setObjectName("lcdSecrecy")
        self.formLayoutSkills.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lcdSecrecy)
        self.lcdObservation = QtWidgets.QLCDNumber(self.layoutWidget_2)
        self.lcdObservation.setObjectName("lcdObservation")
        self.formLayoutSkills.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lcdObservation)
        self.lcdBelief = QtWidgets.QLCDNumber(self.layoutWidget_2)
        self.lcdBelief.setObjectName("lcdBelief")
        self.formLayoutSkills.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lcdBelief)
        self.lcdRepair = QtWidgets.QLCDNumber(self.layoutWidget_2)
        self.lcdRepair.setObjectName("lcdRepair")
        self.formLayoutSkills.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lcdRepair)
        self.lcdSistemOfSecurity = QtWidgets.QLCDNumber(self.layoutWidget_2)
        self.lcdSistemOfSecurity.setObjectName("lcdSistemOfSecurity")
        self.formLayoutSkills.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lcdSistemOfSecurity)
        self.lcdHealing = QtWidgets.QLCDNumber(self.layoutWidget_2)
        self.lcdHealing.setObjectName("lcdHealing")
        self.formLayoutSkills.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lcdHealing)
        self.pointOfSkills = QtWidgets.QLabel(self.layoutWidget_2)
        self.pointOfSkills.setObjectName("pointOfSkills")
        self.formLayoutSkills.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pointOfSkills)
        self.lcdPointOfSkills = QtWidgets.QLCDNumber(self.layoutWidget_2)
        self.lcdPointOfSkills.setObjectName("lcdPointOfSkills")
        self.formLayoutSkills.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lcdPointOfSkills)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.strength.setText(_translate("Dialog", "Сила"))
        self.agility.setText(_translate("Dialog", "Ловкость"))
        self.constitution.setText(_translate("Dialog", "Выносливость"))
        self.intelligence.setText(_translate("Dialog", "Интеллект"))
        self.wisdom.setText(_translate("Dialog", "Мудрость"))
        self.charisma.setText(_translate("Dialog", "Харизма"))
        self.characteristics.setText(_translate("Dialog", "Характеристики"))
        self.pointsOfCharacteristics.setText(_translate("Dialog", "Свободные очки"))
        self.labelName.setText(_translate("Dialog", "Имя:"))
        self.nameOfCharacter.setText(_translate("Dialog", "Не выбрано"))
        self.labelClass.setText(_translate("Dialog", "Класс:"))
        self.classOfCharacter.setText(_translate("Dialog", "Не выбрано"))
        self.labelRace.setText(_translate("Dialog", "Раса:"))
        self.raceOfCharacter.setText(_translate("Dialog", "Не выбрано"))
        self.labelLevel.setText(_translate("Dialog", "Уровень:"))
        self.labelForces.setText(_translate("Dialog", "Силы"))
        self.labelBarrierOfForce.setText(_translate("Dialog", "Барьер Силы"))
        self.labelThrowOfSword.setText(_translate("Dialog", "Бросок меча"))
        self.labelLightning.setText(_translate("Dialog", "Молния"))
        self.labelStun.setText(_translate("Dialog", "Оглушение"))
        self.labelTelekinesis.setText(_translate("Dialog", "Телекинез"))
        self.labelPush.setText(_translate("Dialog", "Толчок"))
        self.labelAcceleration.setText(_translate("Dialog", "Ускорение"))
        self.pointOfForces.setText(_translate("Dialog", "Свободные очки"))
        self.labelSkills.setText(_translate("Dialog", "Навыки"))
        self.lebelComputers.setText(_translate("Dialog", "Компьютеры"))
        self.explosive.setText(_translate("Dialog", "Взрывчатка"))
        self.secrecy.setText(_translate("Dialog", "Скрытность"))
        self.observation.setText(_translate("Dialog", "Внимательность"))
        self.belief.setText(_translate("Dialog", "Убеждение"))
        self.repair.setText(_translate("Dialog", "Ремонт"))
        self.sistemOfSecurity.setText(_translate("Dialog", "Системы Безопастности"))
        self.healing.setText(_translate("Dialog", "Лечение"))
        self.pointOfSkills.setText(_translate("Dialog", "Свободные очки"))


class Ui_DialogCreate(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(782, 520)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(390, 450, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 120, 230, 240))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayoutCharacteristics = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayoutCharacteristics.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayoutCharacteristics.setContentsMargins(0, 0, 0, 0)
        self.formLayoutCharacteristics.setObjectName("formLayoutCharacteristics")
        self.characteristics = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.characteristics.setFont(font)
        self.characteristics.setObjectName("characteristics")
        self.formLayoutCharacteristics.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.characteristics)
        self.strength = QtWidgets.QLabel(self.layoutWidget)
        self.strength.setObjectName("strength")
        self.formLayoutCharacteristics.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.strength)
        self.spinBoxStrength = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxStrength.setObjectName("spinBoxStrength")
        self.formLayoutCharacteristics.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBoxStrength)
        self.agility = QtWidgets.QLabel(self.layoutWidget)
        self.agility.setObjectName("agility")
        self.formLayoutCharacteristics.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.agility)
        self.spinBoxAgility = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxAgility.setObjectName("spinBoxAgility")
        self.formLayoutCharacteristics.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBoxAgility)
        self.constitution = QtWidgets.QLabel(self.layoutWidget)
        self.constitution.setObjectName("constitution")
        self.formLayoutCharacteristics.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.constitution)
        self.spinBoxConstitution = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxConstitution.setObjectName("spinBoxConstitution")
        self.formLayoutCharacteristics.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBoxConstitution)
        self.intelligence = QtWidgets.QLabel(self.layoutWidget)
        self.intelligence.setObjectName("intelligence")
        self.formLayoutCharacteristics.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.intelligence)
        self.spinBoxIntelligence = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxIntelligence.setObjectName("spinBoxIntelligence")
        self.formLayoutCharacteristics.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBoxIntelligence)
        self.wisdom = QtWidgets.QLabel(self.layoutWidget)
        self.wisdom.setObjectName("wisdom")
        self.formLayoutCharacteristics.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.wisdom)
        self.spinBoxWisdom = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxWisdom.setObjectName("spinBoxWisdom")
        self.formLayoutCharacteristics.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.spinBoxWisdom)
        self.charisma = QtWidgets.QLabel(self.layoutWidget)
        self.charisma.setObjectName("charisma")
        self.formLayoutCharacteristics.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.charisma)
        self.spinBoxCharisma = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxCharisma.setObjectName("spinBoxCharisma")
        self.formLayoutCharacteristics.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spinBoxCharisma)
        self.pointsOfCharacteristics = QtWidgets.QLabel(self.layoutWidget)
        self.pointsOfCharacteristics.setObjectName("pointsOfCharacteristics")
        self.formLayoutCharacteristics.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pointsOfCharacteristics)
        self.lcdPointOfCharacteristics = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdPointOfCharacteristics.setObjectName("lcdPointOfCharacteristics")
        self.formLayoutCharacteristics.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lcdPointOfCharacteristics)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 741, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelName = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelName.setObjectName("labelName")
        self.horizontalLayout_2.addWidget(self.labelName)
        self.nameofcharacter = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.nameofcharacter.setObjectName("nameofcharacter")
        self.horizontalLayout_2.addWidget(self.nameofcharacter)
        self.labelClass = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelClass.setObjectName("labelClass")
        self.horizontalLayout_2.addWidget(self.labelClass)
        self.classofcharacter = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.classofcharacter.setObjectName("classofcharacter")
        self.classofcharacter.addItem("")
        self.classofcharacter.addItem("")
        self.classofcharacter.addItem("")
        self.classofcharacter.addItem("")
        self.classofcharacter.addItem("")
        self.classofcharacter.addItem("")
        self.classofcharacter.addItem("")
        self.classofcharacter.addItem("")
        self.classofcharacter.addItem("")
        self.horizontalLayout_2.addWidget(self.classofcharacter)
        self.labelRace = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelRace.setObjectName("labelRace")
        self.horizontalLayout_2.addWidget(self.labelRace)
        self.raceofcharacter = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.raceofcharacter.setObjectName("raceofcharacter")
        self.raceofcharacter.addItem("")
        self.raceofcharacter.addItem("")
        self.raceofcharacter.addItem("")
        self.raceofcharacter.addItem("")
        self.raceofcharacter.addItem("")
        self.raceofcharacter.addItem("")
        self.raceofcharacter.addItem("")
        self.raceofcharacter.addItem("")
        self.horizontalLayout_2.addWidget(self.raceofcharacter)
        self.labelLevel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelLevel.setObjectName("labelLevel")
        self.horizontalLayout_2.addWidget(self.labelLevel)
        self.lcdLevel = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_2)
        self.lcdLevel.setObjectName("lcdLevel")
        self.horizontalLayout_2.addWidget(self.lcdLevel)
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(260, 120, 252, 300))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.formLayoutSkills = QtWidgets.QFormLayout(self.layoutWidget_2)
        self.formLayoutSkills.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayoutSkills.setContentsMargins(0, 0, 0, 0)
        self.formLayoutSkills.setObjectName("formLayoutSkills")
        self.labelSkills = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.labelSkills.setFont(font)
        self.labelSkills.setObjectName("labelSkills")
        self.formLayoutSkills.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelSkills)
        self.lebelComputers = QtWidgets.QLabel(self.layoutWidget_2)
        self.lebelComputers.setObjectName("lebelComputers")
        self.formLayoutSkills.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lebelComputers)
        self.spinBoxComputers = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxComputers.setObjectName("spinBoxComputers")
        self.formLayoutSkills.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBoxComputers)
        self.explosive = QtWidgets.QLabel(self.layoutWidget_2)
        self.explosive.setObjectName("explosive")
        self.formLayoutSkills.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.explosive)
        self.spinBoxExplosive = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxExplosive.setObjectName("spinBoxExplosive")
        self.formLayoutSkills.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBoxExplosive)
        self.secrecy = QtWidgets.QLabel(self.layoutWidget_2)
        self.secrecy.setObjectName("secrecy")
        self.formLayoutSkills.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.secrecy)
        self.spinBoxSecrecy = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxSecrecy.setObjectName("spinBoxSecrecy")
        self.formLayoutSkills.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBoxSecrecy)
        self.observation = QtWidgets.QLabel(self.layoutWidget_2)
        self.observation.setObjectName("observation")
        self.formLayoutSkills.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.observation)
        self.spinBoxObservation = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxObservation.setObjectName("spinBoxObservation")
        self.formLayoutSkills.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBoxObservation)
        self.belief = QtWidgets.QLabel(self.layoutWidget_2)
        self.belief.setObjectName("belief")
        self.formLayoutSkills.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.belief)
        self.spinBoxBelief = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxBelief.setObjectName("spinBoxBelief")
        self.formLayoutSkills.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.spinBoxBelief)
        self.repair = QtWidgets.QLabel(self.layoutWidget_2)
        self.repair.setObjectName("repair")
        self.formLayoutSkills.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.repair)
        self.spinBoxRepair = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxRepair.setObjectName("spinBoxRepair")
        self.formLayoutSkills.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spinBoxRepair)
        self.sistemOfSecurity = QtWidgets.QLabel(self.layoutWidget_2)
        self.sistemOfSecurity.setObjectName("sistemOfSecurity")
        self.formLayoutSkills.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.sistemOfSecurity)
        self.spinBoxSistemOfSecurity = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxSistemOfSecurity.setObjectName("spinBoxSistemOfSecurity")
        self.formLayoutSkills.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.spinBoxSistemOfSecurity)
        self.healing = QtWidgets.QLabel(self.layoutWidget_2)
        self.healing.setObjectName("healing")
        self.formLayoutSkills.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.healing)
        self.spinBoxHealing = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxHealing.setObjectName("spinBoxHealing")
        self.formLayoutSkills.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.spinBoxHealing)
        self.pointOfSkills = QtWidgets.QLabel(self.layoutWidget_2)
        self.pointOfSkills.setObjectName("pointOfSkills")
        self.formLayoutSkills.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pointOfSkills)
        self.lcdPointOfSkills = QtWidgets.QLCDNumber(self.layoutWidget_2)
        self.lcdPointOfSkills.setObjectName("lcdPointOfSkills")
        self.formLayoutSkills.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lcdPointOfSkills)
        self.labelError = QtWidgets.QLabel(Dialog)
        self.labelError.setGeometry(QtCore.QRect(40, 440, 481, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelError.setFont(font)
        self.labelError.setText("")
        self.labelError.setObjectName("labelError")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(530, 100, 231, 321))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 207, 294))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayoutForces = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayoutForces.setContentsMargins(0, 0, 0, 0)
        self.formLayoutForces.setObjectName("formLayoutForces")
        self.labelForces = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.labelForces.setFont(font)
        self.labelForces.setObjectName("labelForces")
        self.formLayoutForces.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelForces)
        self.labelBarrierOfForce = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelBarrierOfForce.setEnabled(True)
        self.labelBarrierOfForce.setObjectName("labelBarrierOfForce")
        self.formLayoutForces.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelBarrierOfForce)
        self.spinBoxBarrierOfForce = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxBarrierOfForce.setObjectName("spinBoxBarrierOfForce")
        self.formLayoutForces.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxBarrierOfForce)
        self.labelThrowOfSword = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelThrowOfSword.setObjectName("labelThrowOfSword")
        self.formLayoutForces.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelThrowOfSword)
        self.spinBoxThrowOfSword = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxThrowOfSword.setObjectName("spinBoxThrowOfSword")
        self.formLayoutForces.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBoxThrowOfSword)
        self.labelLightning = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelLightning.setObjectName("labelLightning")
        self.formLayoutForces.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelLightning)
        self.spinBoxLightning = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxLightning.setObjectName("spinBoxLightning")
        self.formLayoutForces.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBoxLightning)
        self.labelStun = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelStun.setObjectName("labelStun")
        self.formLayoutForces.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelStun)
        self.spinBoxStun = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxStun.setObjectName("spinBoxStun")
        self.formLayoutForces.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBoxStun)
        self.labelTelekinesis = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelTelekinesis.setObjectName("labelTelekinesis")
        self.formLayoutForces.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelTelekinesis)
        self.spinBoxTelekinesis = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxTelekinesis.setObjectName("spinBoxTelekinesis")
        self.formLayoutForces.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBoxTelekinesis)
        self.labelPush = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelPush.setObjectName("labelPush")
        self.formLayoutForces.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.labelPush)
        self.spinBoxPush = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxPush.setObjectName("spinBoxPush")
        self.formLayoutForces.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.spinBoxPush)
        self.labelAcceleration = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelAcceleration.setObjectName("labelAcceleration")
        self.formLayoutForces.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.labelAcceleration)
        self.spinBoxAcceleration = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxAcceleration.setObjectName("spinBoxAcceleration")
        self.formLayoutForces.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spinBoxAcceleration)
        self.pointOfForces = QtWidgets.QLabel(self.formLayoutWidget)
        self.pointOfForces.setObjectName("pointOfForces")
        self.formLayoutForces.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pointOfForces)
        self.lcdPointOfForces = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.lcdPointOfForces.setObjectName("lcdPointOfForces")
        self.formLayoutForces.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lcdPointOfForces)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.characteristics.setText(_translate("Dialog", "Характеристики"))
        self.strength.setText(_translate("Dialog", "Сила"))
        self.agility.setText(_translate("Dialog", "Ловкость"))
        self.constitution.setText(_translate("Dialog", "Выносливость"))
        self.intelligence.setText(_translate("Dialog", "Интеллект"))
        self.wisdom.setText(_translate("Dialog", "Мудрость"))
        self.charisma.setText(_translate("Dialog", "Харизма"))
        self.pointsOfCharacteristics.setText(_translate("Dialog", "Свободные очки"))
        self.labelName.setText(_translate("Dialog", "Имя:"))
        self.labelClass.setText(_translate("Dialog", "Класс:"))
        self.classofcharacter.setItemText(0, _translate("Dialog", "Cитх-Мародёр"))
        self.classofcharacter.setItemText(1, _translate("Dialog", "Лорд ситхов"))
        self.classofcharacter.setItemText(2, _translate("Dialog", "Ситх-Ассасин"))
        self.classofcharacter.setItemText(3, _translate("Dialog", "Джедай-Консул"))
        self.classofcharacter.setItemText(4, _translate("Dialog", "Джедай-Страж"))
        self.classofcharacter.setItemText(5, _translate("Dialog", "Джедай-Хранитель"))
        self.classofcharacter.setItemText(6, _translate("Dialog", "Солдат"))
        self.classofcharacter.setItemText(7, _translate("Dialog", "Разведчик"))
        self.classofcharacter.setItemText(8, _translate("Dialog", "Негодяй"))
        self.labelRace.setText(_translate("Dialog", "Раса:"))
        self.raceofcharacter.setItemText(0, _translate("Dialog", "Человек"))
        self.raceofcharacter.setItemText(1, _translate("Dialog", "Тиссипиасец"))
        self.raceofcharacter.setItemText(2, _translate("Dialog", "Корун"))
        self.raceofcharacter.setItemText(3, _translate("Dialog", "Торгут"))
        self.raceofcharacter.setItemText(4, _translate("Dialog", "Наутоланин"))
        self.raceofcharacter.setItemText(5, _translate("Dialog", "Вуки"))
        self.raceofcharacter.setItemText(6, _translate("Dialog", "Мандалорец"))
        self.raceofcharacter.setItemText(7, _translate("Dialog", "Забрак"))
        self.labelLevel.setText(_translate("Dialog", "Уровень:"))
        self.labelSkills.setText(_translate("Dialog", "Навыки"))
        self.lebelComputers.setText(_translate("Dialog", "Компьютеры"))
        self.explosive.setText(_translate("Dialog", "Взрывчатка"))
        self.secrecy.setText(_translate("Dialog", "Скрытность"))
        self.observation.setText(_translate("Dialog", "Внимательность"))
        self.belief.setText(_translate("Dialog", "Убеждение"))
        self.repair.setText(_translate("Dialog", "Ремонт"))
        self.sistemOfSecurity.setText(_translate("Dialog", "Системы Безопастности"))
        self.healing.setText(_translate("Dialog", "Лечение"))
        self.pointOfSkills.setText(_translate("Dialog", "Свободные очки"))
        self.labelForces.setText(_translate("Dialog", "Силы"))
        self.labelBarrierOfForce.setText(_translate("Dialog", "Барьер Силы"))
        self.labelThrowOfSword.setText(_translate("Dialog", "Бросок меча"))
        self.labelLightning.setText(_translate("Dialog", "Молния"))
        self.labelStun.setText(_translate("Dialog", "Оглушение"))
        self.labelTelekinesis.setText(_translate("Dialog", "Телекинез"))
        self.labelPush.setText(_translate("Dialog", "Толчок"))
        self.labelAcceleration.setText(_translate("Dialog", "Ускорение"))
        self.pointOfForces.setText(_translate("Dialog", "Свободные очки"))


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 386)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelMenu = QtWidgets.QLabel(self.centralwidget)
        self.labelMenu.setGeometry(QtCore.QRect(0, 10, 411, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelMenu.setFont(font)
        self.labelMenu.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMenu.setObjectName("labelMenu")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 50, 461, 222))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonCreate = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonCreate.setObjectName("pushButtonCreate")
        self.verticalLayout.addWidget(self.pushButtonCreate)
        self.pushButtonOpen = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonOpen.setObjectName("pushButtonOpen")
        self.verticalLayout.addWidget(self.pushButtonOpen)
        self.pushButtonCopy = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonCopy.setObjectName("pushButtonCopy")
        self.verticalLayout.addWidget(self.pushButtonCopy)
        self.pushButtonLevelUp = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonLevelUp.setObjectName("pushButtonLevelUp")
        self.verticalLayout.addWidget(self.pushButtonLevelUp)
        self.pushButtonDelete = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.verticalLayout.addWidget(self.pushButtonDelete)
        self.pushButtonExit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.verticalLayout.addWidget(self.pushButtonExit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.listOfCharacters = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.listOfCharacters.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listOfCharacters.setObjectName("listOfCharacters")
        self.horizontalLayout.addWidget(self.listOfCharacters)
        self.labelError = QtWidgets.QLabel(self.centralwidget)
        self.labelError.setGeometry(QtCore.QRect(30, 290, 461, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelError.setFont(font)
        self.labelError.setObjectName("labelError")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelMenu.setText(_translate("MainWindow", "МЕНЮ"))
        self.pushButtonCreate.setText(_translate("MainWindow", "Создать персонажа"))
        self.pushButtonOpen.setText(_translate("MainWindow", "Открыть персонажа"))
        self.pushButtonCopy.setText(_translate("MainWindow", "Копировать персонажа"))
        self.pushButtonLevelUp.setText(_translate("MainWindow", "Повысить уровень персонажа"))
        self.pushButtonDelete.setText(_translate("MainWindow", "Удалить персонажа"))
        self.pushButtonExit.setText(_translate("MainWindow", "Выход"))
        self.labelError.setText(_translate("MainWindow", "TextLabel"))


class Ui_DialogPassword(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(389, 178)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        Dialog.setFont(font)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(19, 40, 351, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelPerson = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelPerson.setObjectName("labelPerson")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelPerson)
        self.choicePerson = QtWidgets.QComboBox(self.formLayoutWidget)
        self.choicePerson.setObjectName("choicePerson")
        self.choicePerson.addItem("")
        self.choicePerson.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.choicePerson)
        self.labelPassword = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelPassword.setObjectName("labelPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelPassword)
        self.lineEditPassword = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditPassword)
        self.buttonEnter = QtWidgets.QPushButton(Dialog)
        self.buttonEnter.setGeometry(QtCore.QRect(260, 140, 101, 31))
        self.buttonEnter.setObjectName("buttonEnter")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelPerson.setText(_translate("Dialog", "Пользователь"))
        self.choicePerson.setItemText(0, _translate("Dialog", "Игрок"))
        self.choicePerson.setItemText(1, _translate("Dialog", "Гейм-мастер"))
        self.labelPassword.setText(_translate("Dialog", "Пароль"))
        self.buttonEnter.setText(_translate("Dialog", "Вход"))


class Ui_DialogLevelUp(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(771, 505)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(410, 460, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(260, 110, 252, 300))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.formLayoutSkills = QtWidgets.QFormLayout(self.layoutWidget_2)
        self.formLayoutSkills.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayoutSkills.setContentsMargins(0, 0, 0, 0)
        self.formLayoutSkills.setObjectName("formLayoutSkills")
        self.labelSkills = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.labelSkills.setFont(font)
        self.labelSkills.setObjectName("labelSkills")
        self.formLayoutSkills.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelSkills)
        self.lebelComputers = QtWidgets.QLabel(self.layoutWidget_2)
        self.lebelComputers.setObjectName("lebelComputers")
        self.formLayoutSkills.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lebelComputers)
        self.spinBoxComputers = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxComputers.setObjectName("spinBoxComputers")
        self.formLayoutSkills.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBoxComputers)
        self.explosive = QtWidgets.QLabel(self.layoutWidget_2)
        self.explosive.setObjectName("explosive")
        self.formLayoutSkills.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.explosive)
        self.spinBoxExplosive = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxExplosive.setObjectName("spinBoxExplosive")
        self.formLayoutSkills.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBoxExplosive)
        self.secrecy = QtWidgets.QLabel(self.layoutWidget_2)
        self.secrecy.setObjectName("secrecy")
        self.formLayoutSkills.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.secrecy)
        self.spinBoxSecrecy = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxSecrecy.setObjectName("spinBoxSecrecy")
        self.formLayoutSkills.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBoxSecrecy)
        self.observation = QtWidgets.QLabel(self.layoutWidget_2)
        self.observation.setObjectName("observation")
        self.formLayoutSkills.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.observation)
        self.spinBoxObservation = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxObservation.setObjectName("spinBoxObservation")
        self.formLayoutSkills.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBoxObservation)
        self.belief = QtWidgets.QLabel(self.layoutWidget_2)
        self.belief.setObjectName("belief")
        self.formLayoutSkills.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.belief)
        self.spinBoxBelief = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxBelief.setObjectName("spinBoxBelief")
        self.formLayoutSkills.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.spinBoxBelief)
        self.repair = QtWidgets.QLabel(self.layoutWidget_2)
        self.repair.setObjectName("repair")
        self.formLayoutSkills.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.repair)
        self.spinBoxRepair = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxRepair.setObjectName("spinBoxRepair")
        self.formLayoutSkills.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spinBoxRepair)
        self.sistemOfSecurity = QtWidgets.QLabel(self.layoutWidget_2)
        self.sistemOfSecurity.setObjectName("sistemOfSecurity")
        self.formLayoutSkills.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.sistemOfSecurity)
        self.spinBoxSistemOfSecurity = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxSistemOfSecurity.setObjectName("spinBoxSistemOfSecurity")
        self.formLayoutSkills.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.spinBoxSistemOfSecurity)
        self.healing = QtWidgets.QLabel(self.layoutWidget_2)
        self.healing.setObjectName("healing")
        self.formLayoutSkills.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.healing)
        self.spinBoxHealing = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxHealing.setObjectName("spinBoxHealing")
        self.formLayoutSkills.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.spinBoxHealing)
        self.pointOfSkills = QtWidgets.QLabel(self.layoutWidget_2)
        self.pointOfSkills.setObjectName("pointOfSkills")
        self.formLayoutSkills.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pointOfSkills)
        self.lcdPointOfSkills = QtWidgets.QLCDNumber(self.layoutWidget_2)
        self.lcdPointOfSkills.setObjectName("lcdPointOfSkills")
        self.formLayoutSkills.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lcdPointOfSkills)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 741, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelName = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelName.setObjectName("labelName")
        self.horizontalLayout_2.addWidget(self.labelName)
        self.nameOfCharacter = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.nameOfCharacter.setObjectName("nameOfCharacter")
        self.horizontalLayout_2.addWidget(self.nameOfCharacter)
        self.labelClass = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelClass.setObjectName("labelClass")
        self.horizontalLayout_2.addWidget(self.labelClass)
        self.classOfCharacter = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.classOfCharacter.setObjectName("classOfCharacter")
        self.horizontalLayout_2.addWidget(self.classOfCharacter)
        self.labelRace = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelRace.setObjectName("labelRace")
        self.horizontalLayout_2.addWidget(self.labelRace)
        self.raceOfCharacter = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.raceOfCharacter.setObjectName("raceOfCharacter")
        self.horizontalLayout_2.addWidget(self.raceOfCharacter)
        self.labelLevel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelLevel.setObjectName("labelLevel")
        self.horizontalLayout_2.addWidget(self.labelLevel)
        self.lcdLevel = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_2)
        self.lcdLevel.setObjectName("lcdLevel")
        self.horizontalLayout_2.addWidget(self.lcdLevel)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(530, 90, 231, 321))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 207, 294))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayoutForces = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayoutForces.setContentsMargins(0, 0, 0, 0)
        self.formLayoutForces.setObjectName("formLayoutForces")
        self.labelForces = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.labelForces.setFont(font)
        self.labelForces.setObjectName("labelForces")
        self.formLayoutForces.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelForces)
        self.labelBarrierOfForce = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelBarrierOfForce.setEnabled(True)
        self.labelBarrierOfForce.setObjectName("labelBarrierOfForce")
        self.formLayoutForces.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelBarrierOfForce)
        self.spinBoxBarrierOfForce = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxBarrierOfForce.setObjectName("spinBoxBarrierOfForce")
        self.formLayoutForces.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxBarrierOfForce)
        self.labelThrowOfSword = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelThrowOfSword.setObjectName("labelThrowOfSword")
        self.formLayoutForces.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelThrowOfSword)
        self.spinBoxThrowOfSword = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxThrowOfSword.setObjectName("spinBoxThrowOfSword")
        self.formLayoutForces.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBoxThrowOfSword)
        self.labelLightning = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelLightning.setObjectName("labelLightning")
        self.formLayoutForces.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelLightning)
        self.spinBoxLightning = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxLightning.setObjectName("spinBoxLightning")
        self.formLayoutForces.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBoxLightning)
        self.labelStun = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelStun.setObjectName("labelStun")
        self.formLayoutForces.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelStun)
        self.spinBoxStun = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxStun.setObjectName("spinBoxStun")
        self.formLayoutForces.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBoxStun)
        self.labelTelekinesis = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelTelekinesis.setObjectName("labelTelekinesis")
        self.formLayoutForces.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelTelekinesis)
        self.spinBoxTelekinesis = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxTelekinesis.setObjectName("spinBoxTelekinesis")
        self.formLayoutForces.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBoxTelekinesis)
        self.labelPush = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelPush.setObjectName("labelPush")
        self.formLayoutForces.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.labelPush)
        self.spinBoxPush = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxPush.setObjectName("spinBoxPush")
        self.formLayoutForces.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.spinBoxPush)
        self.labelAcceleration = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelAcceleration.setObjectName("labelAcceleration")
        self.formLayoutForces.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.labelAcceleration)
        self.spinBoxAcceleration = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxAcceleration.setObjectName("spinBoxAcceleration")
        self.formLayoutForces.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spinBoxAcceleration)
        self.pointOfForces = QtWidgets.QLabel(self.formLayoutWidget)
        self.pointOfForces.setObjectName("pointOfForces")
        self.formLayoutForces.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pointOfForces)
        self.lcdPointOfForces = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.lcdPointOfForces.setObjectName("lcdPointOfForces")
        self.formLayoutForces.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lcdPointOfForces)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 110, 230, 240))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayoutCharacteristics = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayoutCharacteristics.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayoutCharacteristics.setContentsMargins(0, 0, 0, 0)
        self.formLayoutCharacteristics.setObjectName("formLayoutCharacteristics")
        self.characteristics = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.characteristics.setFont(font)
        self.characteristics.setObjectName("characteristics")
        self.formLayoutCharacteristics.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.characteristics)
        self.strength = QtWidgets.QLabel(self.layoutWidget)
        self.strength.setObjectName("strength")
        self.formLayoutCharacteristics.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.strength)
        self.agility = QtWidgets.QLabel(self.layoutWidget)
        self.agility.setObjectName("agility")
        self.formLayoutCharacteristics.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.agility)
        self.spinBoxAgility = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxAgility.setObjectName("spinBoxAgility")
        self.formLayoutCharacteristics.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBoxAgility)
        self.constitution = QtWidgets.QLabel(self.layoutWidget)
        self.constitution.setObjectName("constitution")
        self.formLayoutCharacteristics.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.constitution)
        self.spinBoxConstitution = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxConstitution.setObjectName("spinBoxConstitution")
        self.formLayoutCharacteristics.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBoxConstitution)
        self.intelligence = QtWidgets.QLabel(self.layoutWidget)
        self.intelligence.setObjectName("intelligence")
        self.formLayoutCharacteristics.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.intelligence)
        self.spinBoxIntelligence = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxIntelligence.setObjectName("spinBoxIntelligence")
        self.formLayoutCharacteristics.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBoxIntelligence)
        self.wisdom = QtWidgets.QLabel(self.layoutWidget)
        self.wisdom.setObjectName("wisdom")
        self.formLayoutCharacteristics.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.wisdom)
        self.spinBoxWisdom = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxWisdom.setObjectName("spinBoxWisdom")
        self.formLayoutCharacteristics.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.spinBoxWisdom)
        self.charisma = QtWidgets.QLabel(self.layoutWidget)
        self.charisma.setObjectName("charisma")
        self.formLayoutCharacteristics.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.charisma)
        self.spinBoxCharisma = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxCharisma.setObjectName("spinBoxCharisma")
        self.formLayoutCharacteristics.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spinBoxCharisma)
        self.pointsOfCharacteristics = QtWidgets.QLabel(self.layoutWidget)
        self.pointsOfCharacteristics.setObjectName("pointsOfCharacteristics")
        self.formLayoutCharacteristics.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pointsOfCharacteristics)
        self.lcdPointOfCharacteristics = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdPointOfCharacteristics.setObjectName("lcdPointOfCharacteristics")
        self.formLayoutCharacteristics.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lcdPointOfCharacteristics)
        self.spinBoxStrength = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxStrength.setObjectName("spinBoxStrength")
        self.formLayoutCharacteristics.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBoxStrength)
        self.labelError = QtWidgets.QLabel(Dialog)
        self.labelError.setGeometry(QtCore.QRect(20, 420, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelError.setFont(font)
        self.labelError.setText("")
        self.labelError.setObjectName("labelError")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelSkills.setText(_translate("Dialog", "Навыки"))
        self.lebelComputers.setText(_translate("Dialog", "Компьютеры"))
        self.explosive.setText(_translate("Dialog", "Взрывчатка"))
        self.secrecy.setText(_translate("Dialog", "Скрытность"))
        self.observation.setText(_translate("Dialog", "Внимательность"))
        self.belief.setText(_translate("Dialog", "Убеждение"))
        self.repair.setText(_translate("Dialog", "Ремонт"))
        self.sistemOfSecurity.setText(_translate("Dialog", "Системы Безопастности"))
        self.healing.setText(_translate("Dialog", "Лечение"))
        self.pointOfSkills.setText(_translate("Dialog", "Свободные очки"))
        self.labelName.setText(_translate("Dialog", "Имя:"))
        self.nameOfCharacter.setText(_translate("Dialog", "Не выбрано"))
        self.labelClass.setText(_translate("Dialog", "Класс:"))
        self.classOfCharacter.setText(_translate("Dialog", "Не выбрано"))
        self.labelRace.setText(_translate("Dialog", "Раса:"))
        self.raceOfCharacter.setText(_translate("Dialog", "Не выбрано"))
        self.labelLevel.setText(_translate("Dialog", "Уровень:"))
        self.labelForces.setText(_translate("Dialog", "Силы"))
        self.labelBarrierOfForce.setText(_translate("Dialog", "Барьер Силы"))
        self.labelThrowOfSword.setText(_translate("Dialog", "Бросок меча"))
        self.labelLightning.setText(_translate("Dialog", "Молния"))
        self.labelStun.setText(_translate("Dialog", "Оглушение"))
        self.labelTelekinesis.setText(_translate("Dialog", "Телекинез"))
        self.labelPush.setText(_translate("Dialog", "Толчок"))
        self.labelAcceleration.setText(_translate("Dialog", "Ускорение"))
        self.pointOfForces.setText(_translate("Dialog", "Свободные очки"))
        self.characteristics.setText(_translate("Dialog", "Характеристики"))
        self.strength.setText(_translate("Dialog", "Сила"))
        self.agility.setText(_translate("Dialog", "Ловкость"))
        self.constitution.setText(_translate("Dialog", "Выносливость"))
        self.intelligence.setText(_translate("Dialog", "Интеллект"))
        self.wisdom.setText(_translate("Dialog", "Мудрость"))
        self.charisma.setText(_translate("Dialog", "Харизма"))
        self.pointsOfCharacteristics.setText(_translate("Dialog", "Свободные очки"))


