# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'levelUp.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogLevelUp(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(771, 505)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(410, 460, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(260, 110, 252, 300))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.formLayoutSkills = QtWidgets.QFormLayout(self.layoutWidget_2)
        self.formLayoutSkills.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayoutSkills.setContentsMargins(0, 0, 0, 0)
        self.formLayoutSkills.setObjectName("formLayoutSkills")
        self.labelSkills = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.labelSkills.setFont(font)
        self.labelSkills.setObjectName("labelSkills")
        self.formLayoutSkills.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelSkills)
        self.lebelComputers = QtWidgets.QLabel(self.layoutWidget_2)
        self.lebelComputers.setObjectName("lebelComputers")
        self.formLayoutSkills.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lebelComputers)
        self.spinBoxComputers = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxComputers.setObjectName("spinBoxComputers")
        self.formLayoutSkills.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBoxComputers)
        self.explosive = QtWidgets.QLabel(self.layoutWidget_2)
        self.explosive.setObjectName("explosive")
        self.formLayoutSkills.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.explosive)
        self.spinBoxExplosive = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxExplosive.setObjectName("spinBoxExplosive")
        self.formLayoutSkills.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBoxExplosive)
        self.secrecy = QtWidgets.QLabel(self.layoutWidget_2)
        self.secrecy.setObjectName("secrecy")
        self.formLayoutSkills.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.secrecy)
        self.spinBoxSecrecy = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxSecrecy.setObjectName("spinBoxSecrecy")
        self.formLayoutSkills.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBoxSecrecy)
        self.observation = QtWidgets.QLabel(self.layoutWidget_2)
        self.observation.setObjectName("observation")
        self.formLayoutSkills.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.observation)
        self.spinBoxObservation = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxObservation.setObjectName("spinBoxObservation")
        self.formLayoutSkills.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBoxObservation)
        self.belief = QtWidgets.QLabel(self.layoutWidget_2)
        self.belief.setObjectName("belief")
        self.formLayoutSkills.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.belief)
        self.spinBoxBelief = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxBelief.setObjectName("spinBoxBelief")
        self.formLayoutSkills.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.spinBoxBelief)
        self.repair = QtWidgets.QLabel(self.layoutWidget_2)
        self.repair.setObjectName("repair")
        self.formLayoutSkills.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.repair)
        self.spinBoxRepair = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxRepair.setObjectName("spinBoxRepair")
        self.formLayoutSkills.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spinBoxRepair)
        self.sistemOfSecurity = QtWidgets.QLabel(self.layoutWidget_2)
        self.sistemOfSecurity.setObjectName("sistemOfSecurity")
        self.formLayoutSkills.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.sistemOfSecurity)
        self.spinBoxSistemOfSecurity = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxSistemOfSecurity.setObjectName("spinBoxSistemOfSecurity")
        self.formLayoutSkills.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.spinBoxSistemOfSecurity)
        self.healing = QtWidgets.QLabel(self.layoutWidget_2)
        self.healing.setObjectName("healing")
        self.formLayoutSkills.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.healing)
        self.spinBoxHealing = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBoxHealing.setObjectName("spinBoxHealing")
        self.formLayoutSkills.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.spinBoxHealing)
        self.pointOfSkills = QtWidgets.QLabel(self.layoutWidget_2)
        self.pointOfSkills.setObjectName("pointOfSkills")
        self.formLayoutSkills.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pointOfSkills)
        self.lcdPointOfSkills = QtWidgets.QLCDNumber(self.layoutWidget_2)
        self.lcdPointOfSkills.setObjectName("lcdPointOfSkills")
        self.formLayoutSkills.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lcdPointOfSkills)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 741, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelName = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelName.setObjectName("labelName")
        self.horizontalLayout_2.addWidget(self.labelName)
        self.nameOfCharacter = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.nameOfCharacter.setObjectName("nameOfCharacter")
        self.horizontalLayout_2.addWidget(self.nameOfCharacter)
        self.labelClass = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelClass.setObjectName("labelClass")
        self.horizontalLayout_2.addWidget(self.labelClass)
        self.classOfCharacter = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.classOfCharacter.setObjectName("classOfCharacter")
        self.horizontalLayout_2.addWidget(self.classOfCharacter)
        self.labelRace = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelRace.setObjectName("labelRace")
        self.horizontalLayout_2.addWidget(self.labelRace)
        self.raceOfCharacter = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.raceOfCharacter.setObjectName("raceOfCharacter")
        self.horizontalLayout_2.addWidget(self.raceOfCharacter)
        self.labelLevel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelLevel.setObjectName("labelLevel")
        self.horizontalLayout_2.addWidget(self.labelLevel)
        self.lcdLevel = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_2)
        self.lcdLevel.setObjectName("lcdLevel")
        self.horizontalLayout_2.addWidget(self.lcdLevel)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(530, 90, 231, 321))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 207, 294))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayoutForces = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayoutForces.setContentsMargins(0, 0, 0, 0)
        self.formLayoutForces.setObjectName("formLayoutForces")
        self.labelForces = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.labelForces.setFont(font)
        self.labelForces.setObjectName("labelForces")
        self.formLayoutForces.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelForces)
        self.labelBarrierOfForce = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelBarrierOfForce.setEnabled(True)
        self.labelBarrierOfForce.setObjectName("labelBarrierOfForce")
        self.formLayoutForces.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelBarrierOfForce)
        self.spinBoxBarrierOfForce = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxBarrierOfForce.setObjectName("spinBoxBarrierOfForce")
        self.formLayoutForces.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxBarrierOfForce)
        self.labelThrowOfSword = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelThrowOfSword.setObjectName("labelThrowOfSword")
        self.formLayoutForces.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelThrowOfSword)
        self.spinBoxThrowOfSword = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxThrowOfSword.setObjectName("spinBoxThrowOfSword")
        self.formLayoutForces.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBoxThrowOfSword)
        self.labelLightning = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelLightning.setObjectName("labelLightning")
        self.formLayoutForces.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelLightning)
        self.spinBoxLightning = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxLightning.setObjectName("spinBoxLightning")
        self.formLayoutForces.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBoxLightning)
        self.labelStun = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelStun.setObjectName("labelStun")
        self.formLayoutForces.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelStun)
        self.spinBoxStun = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxStun.setObjectName("spinBoxStun")
        self.formLayoutForces.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBoxStun)
        self.labelTelekinesis = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelTelekinesis.setObjectName("labelTelekinesis")
        self.formLayoutForces.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelTelekinesis)
        self.spinBoxTelekinesis = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxTelekinesis.setObjectName("spinBoxTelekinesis")
        self.formLayoutForces.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBoxTelekinesis)
        self.labelPush = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelPush.setObjectName("labelPush")
        self.formLayoutForces.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.labelPush)
        self.spinBoxPush = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxPush.setObjectName("spinBoxPush")
        self.formLayoutForces.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.spinBoxPush)
        self.labelAcceleration = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelAcceleration.setObjectName("labelAcceleration")
        self.formLayoutForces.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.labelAcceleration)
        self.spinBoxAcceleration = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxAcceleration.setObjectName("spinBoxAcceleration")
        self.formLayoutForces.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spinBoxAcceleration)
        self.pointOfForces = QtWidgets.QLabel(self.formLayoutWidget)
        self.pointOfForces.setObjectName("pointOfForces")
        self.formLayoutForces.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pointOfForces)
        self.lcdPointOfForces = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.lcdPointOfForces.setObjectName("lcdPointOfForces")
        self.formLayoutForces.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lcdPointOfForces)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 110, 230, 240))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayoutCharacteristics = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayoutCharacteristics.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayoutCharacteristics.setContentsMargins(0, 0, 0, 0)
        self.formLayoutCharacteristics.setObjectName("formLayoutCharacteristics")
        self.characteristics = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.characteristics.setFont(font)
        self.characteristics.setObjectName("characteristics")
        self.formLayoutCharacteristics.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.characteristics)
        self.strength = QtWidgets.QLabel(self.layoutWidget)
        self.strength.setObjectName("strength")
        self.formLayoutCharacteristics.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.strength)
        self.agility = QtWidgets.QLabel(self.layoutWidget)
        self.agility.setObjectName("agility")
        self.formLayoutCharacteristics.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.agility)
        self.spinBoxAgility = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxAgility.setObjectName("spinBoxAgility")
        self.formLayoutCharacteristics.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBoxAgility)
        self.constitution = QtWidgets.QLabel(self.layoutWidget)
        self.constitution.setObjectName("constitution")
        self.formLayoutCharacteristics.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.constitution)
        self.spinBoxConstitution = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxConstitution.setObjectName("spinBoxConstitution")
        self.formLayoutCharacteristics.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBoxConstitution)
        self.intelligence = QtWidgets.QLabel(self.layoutWidget)
        self.intelligence.setObjectName("intelligence")
        self.formLayoutCharacteristics.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.intelligence)
        self.spinBoxIntelligence = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxIntelligence.setObjectName("spinBoxIntelligence")
        self.formLayoutCharacteristics.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBoxIntelligence)
        self.wisdom = QtWidgets.QLabel(self.layoutWidget)
        self.wisdom.setObjectName("wisdom")
        self.formLayoutCharacteristics.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.wisdom)
        self.spinBoxWisdom = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxWisdom.setObjectName("spinBoxWisdom")
        self.formLayoutCharacteristics.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.spinBoxWisdom)
        self.charisma = QtWidgets.QLabel(self.layoutWidget)
        self.charisma.setObjectName("charisma")
        self.formLayoutCharacteristics.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.charisma)
        self.spinBoxCharisma = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxCharisma.setObjectName("spinBoxCharisma")
        self.formLayoutCharacteristics.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spinBoxCharisma)
        self.pointsOfCharacteristics = QtWidgets.QLabel(self.layoutWidget)
        self.pointsOfCharacteristics.setObjectName("pointsOfCharacteristics")
        self.formLayoutCharacteristics.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pointsOfCharacteristics)
        self.lcdPointOfCharacteristics = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdPointOfCharacteristics.setObjectName("lcdPointOfCharacteristics")
        self.formLayoutCharacteristics.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lcdPointOfCharacteristics)
        self.spinBoxStrength = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxStrength.setObjectName("spinBoxStrength")
        self.formLayoutCharacteristics.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBoxStrength)
        self.labelError = QtWidgets.QLabel(Dialog)
        self.labelError.setGeometry(QtCore.QRect(20, 420, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelError.setFont(font)
        self.labelError.setText("")
        self.labelError.setObjectName("labelError")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelSkills.setText(_translate("Dialog", "Навыки"))
        self.lebelComputers.setText(_translate("Dialog", "Компьютеры"))
        self.explosive.setText(_translate("Dialog", "Взрывчатка"))
        self.secrecy.setText(_translate("Dialog", "Скрытность"))
        self.observation.setText(_translate("Dialog", "Внимательность"))
        self.belief.setText(_translate("Dialog", "Убеждение"))
        self.repair.setText(_translate("Dialog", "Ремонт"))
        self.sistemOfSecurity.setText(_translate("Dialog", "Системы Безопастности"))
        self.healing.setText(_translate("Dialog", "Лечение"))
        self.pointOfSkills.setText(_translate("Dialog", "Свободные очки"))
        self.labelName.setText(_translate("Dialog", "Имя:"))
        self.nameOfCharacter.setText(_translate("Dialog", "Не выбрано"))
        self.labelClass.setText(_translate("Dialog", "Класс:"))
        self.classOfCharacter.setText(_translate("Dialog", "Не выбрано"))
        self.labelRace.setText(_translate("Dialog", "Раса:"))
        self.raceOfCharacter.setText(_translate("Dialog", "Не выбрано"))
        self.labelLevel.setText(_translate("Dialog", "Уровень:"))
        self.labelForces.setText(_translate("Dialog", "Силы"))
        self.labelBarrierOfForce.setText(_translate("Dialog", "Барьер Силы"))
        self.labelThrowOfSword.setText(_translate("Dialog", "Бросок меча"))
        self.labelLightning.setText(_translate("Dialog", "Молния"))
        self.labelStun.setText(_translate("Dialog", "Оглушение"))
        self.labelTelekinesis.setText(_translate("Dialog", "Телекинез"))
        self.labelPush.setText(_translate("Dialog", "Толчок"))
        self.labelAcceleration.setText(_translate("Dialog", "Ускорение"))
        self.pointOfForces.setText(_translate("Dialog", "Свободные очки"))
        self.characteristics.setText(_translate("Dialog", "Характеристики"))
        self.strength.setText(_translate("Dialog", "Сила"))
        self.agility.setText(_translate("Dialog", "Ловкость"))
        self.constitution.setText(_translate("Dialog", "Выносливость"))
        self.intelligence.setText(_translate("Dialog", "Интеллект"))
        self.wisdom.setText(_translate("Dialog", "Мудрость"))
        self.charisma.setText(_translate("Dialog", "Харизма"))
        self.pointsOfCharacteristics.setText(_translate("Dialog", "Свободные очки"))
